import type { Guest } from './types';

const photo = (fileName: string) => `/guests/${encodeURIComponent(fileName)}`;

export const GUESTS: Guest[] = [
    {
        id: 1,
        fullName: 'Андрей',
        photo: photo('Андрей.jpg'),
        category1: 'Молодожены',
        category2: 'Жених',
        color: '#C4A35A',
        shortDescription: 'Разработчик, любит PS5',
        fullDescription:
            'Спокойный добрейшей души человек с огромным запасом терпения. Имеет черный гардероб. Любит соджу с пивом.',
    },
    {
        id: 2,
        fullName: 'Вероника',
        photo: photo('Вероника.jpg'),
        category1: 'Молодожены',
        category2: 'Невеста',
        color: '#C4A35A',
        shortDescription: 'Любит Гарри Поттера и аниме',
        fullDescription:
            'Любит читать художественную литературу, коллекционирует аниме-фигурки. «Типичная Дева», любит планы и списки.',
    },
    {
        id: 3,
        fullName: 'Усков Олег Юрьевич',
        photo: photo('Олег.jpg'),
        category1: 'Со стороны невесты',
        category2: 'Родители',
        color: '#7A6B8A',
        shortDescription: 'Военный на пенсии, айкидо',
        fullDescription:
            'Человек «всё делаю по правилам», обладает тонким чувством справедливости. Любит активность и спорт.',
    },
    {
        id: 4,
        fullName: 'Ускова Оксана Анатольевна',
        photo: photo('Оксана.jpg'),
        category1: 'Со стороны невесты',
        category2: 'Родители',
        color: '#7A6B8A',
        shortDescription: 'Печет вкусные торты',
        fullDescription:
            'Очень мудрая и спокойная, всегда поддержит и поможет. Любит кошек и читать.',
    },
    {
        id: 5,
        fullName: 'Тротно Эвелина',
        photo: photo('Эвелина.jpg'),
        category1: 'Со стороны невесты',
        category2: 'Двоюродные',
        color: '#7A6B8A',
        shortDescription: 'Работает в Скорой помощи',
        fullDescription: 'Добрейший души человек, любит аниме и BTS. С детства играли вместе.',
    },
    {
        id: 6,
        fullName: 'Петров Вячеслав Викторович',
        photo: photo('Вячеслав.jpg'),
        category1: 'Со стороны жениха',
        category2: 'Родители',
        color: '#4A6B7C',
        shortDescription: 'Любит рыбалку и анекдоты',
        fullDescription: 'Спокойный и тихий человек. У него целая рота цыпочек.',
    },
    {
        id: 7,
        fullName: 'Вихрова Анна Николаевна',
        photo: photo('Анна.jpg'),
        category1: 'Со стороны жениха',
        category2: 'Родители',
        color: '#4A6B7C',
        shortDescription: 'За всеми ухаживает',
        fullDescription:
            'Никогда не сидит без дела, готовит вкусные тортики. Посмотрела 4 раза сериал «Постучись в мою дверь».',
    },
    {
        id: 8,
        fullName: 'Вихрова Екатерина Михайловна',
        photo: photo('Катя.jpg'),
        category1: 'Со стороны жениха',
        category2: 'Братья/Сестры',
        color: '#4A6B7C',
        shortDescription: 'PR-щик в декрете',
        fullDescription:
            'Помогала жениху делать уроки в школе. Решила освободить жениха от физкультуры, сломав ему спину.',
    },
    {
        id: 9,
        fullName: 'Максимов Андрей',
        photo: photo('АндрейМаксимов.jpg'),
        category1: 'Со стороны жениха',
        category2: 'Муж сестры жениха',
        color: '#4A6B7C',
        shortDescription: 'Большой начальник на заводе',
        fullDescription:
            'Улыбается реже, чем Артемий Лебедев. Любимая группа — Красная плесень.',
    },
    {
        id: 10,
        fullName: 'Лаврова Вика',
        photo: photo('Вика.jpg'),
        category1: 'Со стороны невесты',
        category2: 'Подруги',
        color: '#5B7A68',
        shortDescription: 'Научит английскому и даст ценный совет',
        fullDescription: 'Огромная коллекция фигурок-аниме. Фанат Южной Кореи и Японии.',
    },
    {
        id: 11,
        fullName: 'Лавров Серега',
        photo: photo('Серега.jpg'),
        category1: 'Со стороны невесты',
        category2: 'Друзья',
        color: '#5B7A68',
        shortDescription: 'Большой начальник на заводе',
        fullDescription:
            'Знает сколько калорий в любом продукте. Любит настольные игры, пытается склонить к D&D.',
    },
    {
        id: 12,
        fullName: 'Мила',
        photo: photo('Мила.jpg'),
        category1: 'Со стороны невесты',
        category2: 'Подруги',
        color: '#5B7A68',
        shortDescription: 'Фитнес и йога тренер',
        fullDescription:
            'Невероятно жизнерадостный человек. Держит в страхе всех бариста в Воронеже.',
    },
    {
        id: 13,
        fullName: 'Спутник Милы — Сергей',
        photo: photo('Сергей.jpg'),
        category1: 'Со стороны невесты',
        category2: 'Друзья',
        color: '#5B7A68',
        shortDescription: 'Работает аналитиком, любит тачки',
        fullDescription: 'Ради Милы приходил на йогу в 6 утра.',
    },
    {
        id: 14,
        fullName: 'Жаркова Марина',
        photo: photo('Марина.jpg'),
        category1: 'Со стороны невесты',
        category2: 'Подруги',
        color: '#5B7A68',
        shortDescription: 'Стоматолог-косметолог',
        fullDescription:
            'Сделает из любого лица красивое и молодое. Родилась в Норильске, её не испугать питерской погодой.',
    },
    {
        id: 15,
        fullName: 'Федоров Александр',
        photo: photo('Саня.jpg'),
        category1: 'Со стороны жениха',
        category2: 'Друзья',
        color: '#5B7A68',
        shortDescription: 'Следит за городом через камеры',
        fullDescription: 'Собрал всю коллекцию Pringles. Чемпион литр-бола. Любит Ягермейстер.',
    },
    {
        id: 16,
        fullName: 'Дроздова Нина',
        photo: photo('Нина.jpg'),
        category1: 'Со стороны жениха',
        category2: 'Подруги',
        color: '#5B7A68',
        shortDescription: 'Круглый год на досках (сёрф/сноуборд)',
        fullDescription: 'Гордится своей кошкой Муфлей. Имеет пояс по тхэквондо.',
    },
    {
        id: 17,
        fullName: 'Спутник Нины — Ярослав',
        photo: photo('Ярик.jpg'),
        category1: 'Со стороны жениха',
        category2: 'Друзья',
        color: '#5B7A68',
        shortDescription: 'Активный образ жизни',
        fullDescription: 'Тусят с Ниной на досках зимой и летом.',
    },
    {
        id: 18,
        fullName: 'Жулин Владислав',
        photo: photo('Влад.jpg'),
        category1: 'Со стороны жениха',
        category2: 'Друзья',
        color: '#5B7A68',
        shortDescription: 'Коренной петербуржец',
        fullDescription: 'Человек-шазам, человек-карта. Однажды побрился налысо за 50 000 тенге.',
    },
    {
        id: 19,
        fullName: 'Золотарев Александр',
        photo: photo('Александр.jpg'),
        category1: 'Со стороны жениха',
        category2: 'Друзья',
        color: '#5B7A68',
        shortDescription: 'Брат-близнец Влада от другой мамы',
        fullDescription: 'Поднимал кофейный бизнес Уфы. Кличка «Анимешник».',
    },
    {
        id: 20,
        fullName: 'Спутница Александра — Дарья',
        photo: photo('Дарья.jpg'),
        category1: 'Со стороны жениха',
        category2: 'Подруги',
        color: '#5B7A68',
        shortDescription: 'На работе её парень — начальник, дома они меняются местами',
        fullDescription:
            'Не может решить, что любит больше — сладкое или своего Александра. Предпочитает леопардовые вещи не из‑за моды, а из‑за характера.',
    },
    {
        id: 21,
        fullName: 'Юганов Алексей',
        photo: photo('Алексей.jpg'),
        category1: 'Со стороны жениха',
        category2: 'Друзья',
        color: '#5B7A68',
        shortDescription: 'Сваха всея Руси, Гузеева на минималках',
        fullDescription: 'Будет напоминать о чем-либо чаще чем Дуолинго.',
    },
];

export const GUEST_CATEGORIES = [
    ...new Set(GUESTS.map((guest) => guest.category1).filter(Boolean)),
];
